#!/usr/bin/env sh

set -e

TAG="latest"

while [ $# -gt 0 ]; do
  case "$1" in
    --tag)
      TAG="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

DOCKER_DEFAULT_PLATFORM="linux/amd64" docker build -t "agentkai-api:$TAG" .
