name: Push checks
on:
  pull_request:

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync
        run: uv sync

      - name: Lint
        run: scripts/lint

  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/package.json
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync
        run: |
          uv sync

      - name: Setup .env
        run: |
          cat <<EOF > .env
          LLM_PROVIDER_KEY=${{ secrets.MISTRAL_API_KEY }}
          MAPTILER_API_KEY=${{ secrets.MAPTILER_KEY }}
          LOG_LEVEL=DEBUG
          VERSION="x.x.x-testing"
          EOF

      - name: Test
        run: scripts/test

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/package.json
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd backend
          scripts/build-docker-image

  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd frontend
          scripts/build-docker-image --maptiler-key ${{ secrets.MAPTILER_KEY }}
